- name: Configure arr Debian VM
  hosts: arr
  become: true
  gather_facts: true
  vars:
    user: "{{ inventory_hostname }}"
    media: media
  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name:
          - qemu-guest-agent
          - passwd
          - ca-certificates
          - curl
        state: present
        update_cache: true
    - name: Enable QEMU guest agent
      ansible.builtin.systemd_service:
        name: qemu-guest-agent
        state: started
        enabled: true
    - name: Rename default group (GID 1000) to 'media'
      ansible.builtin.command:
        cmd: "groupmod -n {{ media }} {{ user }}"
      ignore_errors: true
    - name: Add user to media group and keep sudo
      ansible.builtin.user:
        name: "{{ user }}"
        group: "{{ media }}"
        groups: sudo
        append: true
    - name: Ensure /etc/apt/keyrings directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
    - name: Download Docker official GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
    - name: Add Docker repository
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/docker.sources
        mode: '0644'
        content: |
          Types: deb
          URIs: https://download.docker.com/linux/debian
          Suites: {{ ansible_facts['distribution_release'] }}
          Components: stable
          Architectures: {{ 'amd64' if ansible_facts['architecture'] == 'x86_64' else ansible_facts['architecture'] }}
          Signed-By: /etc/apt/keyrings/docker.asc
    - name: Install docker packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true
    - name: Enable docker daemon
      ansible.builtin.systemd_service:
        name: docker
        state: started
        enabled: true
    - name: Ensure compose directory exists
      ansible.builtin.file:
        path: /opt/servarr
        state: directory
        owner: "{{ user }}"
        group: "{{ media }}"
        mode: '0755'
    - name: Copy compose file
      ansible.builtin.copy:
        src: files/docker-compose.yaml
        dest: /opt/servarr/docker-compose.yml
        owner: "{{ user }}"
        group: "{{ media }}"
        mode: '0644'
    - name: Create Docker Network
      ansible.builtin.command:
        cmd: docker network create servarr_default
        chdir: /opt/servarr
      ignore_errors: true
    - name: Add disks to fstab
      ansible.builtin.blockinfile:
        state: present
        dest: /etc/fstab
        marker: "### {mark} Mount disks ANSIBLE MANAGED BLOCK"
        prepend_newline: true
        insertafter: EOF
        content: "{{ lookup('file', 'files/fstab.part') }}"
    - name: Reload fstab
      ansible.builtin.systemd_service:
        name: remote-fs.target
        daemon_reload: true
        state: restarted
    - name: Start Docker Compose stack
      ansible.builtin.command:
        cmd: docker compose up -d --remove-orphans
        chdir: /opt/servarr
    - name: Wait 5 seconds for container initialization
      ansible.builtin.pause:
        seconds: 5
    - name: Fetch qbittorrent dummy password
      command: docker logs --tail 5 qbittorrent
      register: qb
    - name: Display last 5 log lines
      debug:
        msg: "{{ qb.stdout }}"
