- name: Setup disks sharing with Samba
  hosts: homelab
  become: true
  gather_facts: false
  tasks:
    - name: Install
      ansible.builtin.dnf:
        name: samba
        state: present
        update_cache: true
    - name: Copy config
      ansible.builtin.copy:
        src: files/etc/samba/smb.conf
        dest: /etc/samba/smb.conf
        owner: root
        group: root
        mode: '0644'
    # TODO: SELinux. See README
    - name: Enable service
      ansible.builtin.systemd_service:
        name: smb.service
        state: started
        enabled: true
