[Application]
FileLogger\Age=1
FileLogger\AgeType=1
FileLogger\Backup=true
FileLogger\DeleteOld=true
FileLogger\Enabled=true
FileLogger\MaxSizeBytes=66560
FileLogger\Path=/app/qBittorrent/data/logs

[BitTorrent]
Session\DefaultSavePath=/data/torrents
Session\DisableAutoTMMByDefault=false
Session\ExcludedFileNames=
Session\Port=54929
Session\QueueingSystemEnabled=false
Session\SSL\Port=21533
Session\UseCategoryPathsInManualMode=true

[Core]
AutoDeleteAddedTorrentFile=Never

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=8

[Preferences]
General\Locale=en
MailNotification\req_auth=true
WebUI\AuthSubnetWhitelist=192.168.0.0/24
WebUI\AuthSubnetWhitelistEnabled=true
WebUI\Password_PBKDF2="@ByteArray(+nZY2gdxdrIBI4GgsvcKaQ==:L2RcHAOD+IsyqsTz5RnU7ZEejLExPgIoYkEEn4Awr3QNBpXbjUiAtkNWLOhnqpN0EuGxK3pY9MzEPfFQaKF6Ng==)"
WebUI\Username=qbittorrent

[RSS]
AutoDownloader\DownloadRepacks=true
AutoDownloader\SmartEpisodeFilter=s(\\d+)e(\\d+), (\\d+)x(\\d+), "(\\d{4}[.\\-]\\d{1,2}[.\\-]\\d{1,2})", "(\\d{1,2}[.\\-]\\d{1,2}[.\\-]\\d{4})"
