all:
  children:
    proxmox:
      hosts:
        proxmox_host:
          ansible_host: 192.168.0.99
          ansible_user: root
    vm:
      hosts:
        arr:
          ansible_host: 192.168.0.100
          ansible_user: arr
          vm_id: 100
    lxc:
      hosts:
        syncthing:
          ansible_host: 192.168.0.101
          vm_id: 101
