all:
  children:
    proxmox:
      hosts:
        proxmox_host:
          ansible_host: 192.168.0.99
    vm:
      hosts:
        arr:
          ansible_host: 192.168.0.100
          ansible_user: arr
          vm_id: 100
