- name: Homelab setup
  hosts: proxmox
  vars_files:
    -  secrets.yaml

  tasks:
    - name: Start container
      community.proxmox.proxmox:
        api_host: "{{ ansible_host }}"
        api_user: "{{ vault_proxmox_user }}@pam"
        api_password: "{{ vault_proxmox_password }}"
        vmid: 105
        state: started
      delegate_to: localhost

    - name: Stop container
      community.proxmox.proxmox:
        api_host: "{{ ansible_host }}"
        api_user: "{{ vault_proxmox_user }}@pam"
        api_password: "{{ vault_proxmox_password }}"
        vmid: 105
        state: stopped
      delegate_to: localhost
