- name: Setup OpenSSH on Alpine containers
  hosts: lxcs
  gather_facts: false


  tasks:
    - name: 1. Install OpenSSH Package
      ansible.builtin.command:
        cmd: "pct exec {{ vm_id }} -- apk update"
      delegate_to: proxmox_host
      
    - name: 2. Install OpenSSH Package
      ansible.builtin.command:
        cmd: "pct exec {{ vm_id }} -- apk add openssh"
      delegate_to: proxmox_host

    - name: 3. Enable SSH Boot Service
      ansible.builtin.command:
        cmd: "pct exec {{ vm_id }} -- rc-update add sshd default"
      delegate_to: proxmox_host

    - name: 4. Start SSH Daemon Live
      ansible.builtin.command:
        cmd: "pct exec {{ vm_id }} -- rc-service sshd start"
      delegate_to: proxmox_host
