- name: Set up Jellyfin LXC
  hosts: jellyfin
  gather_facts: false
  tasks:
    - name: Install server
      community.general.apk:
        name: jellyfin
        state: present
    - name: Install web client
      community.general.apk:
        name: jellyfin-web
        state: present
    - name: Enable web client
      ansible.builtin.replace:
        path: "/etc/conf.d/jellyfin"
        regexp: "--nowebclient"
        replace: ""
    - name: Start service
      ansible.builtin.command:
        cmd: rc-service jellyfin start
    - name: Enable service
      ansible.builtin.command:
        cmd: rc-update add jellyfin default
